-- AP base (placeholder) — cria apenas se não existir
BEGIN;

CREATE TABLE IF NOT EXISTS public.contas_pagar_corporativas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filial_id BIGINT,
  credor_id BIGINT,
  descricao TEXT NOT NULL,
  valor_total NUMERIC(14,2) NOT NULL DEFAULT 0,
  categoria_id BIGINT,
  dt_vencimento DATE,
  dt_emissao DATE,
  status TEXT NOT NULL DEFAULT 'aberta',
  observacoes TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.parcelas_conta_pagar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conta_pagar_id BIGINT NOT NULL REFERENCES public.contas_pagar_corporativas(id) ON DELETE CASCADE,
  num_parcela INT NOT NULL DEFAULT 1,
  data_vencimento DATE NOT NULL,
  valor_parcela NUMERIC(14,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'a_vencer',
  pago_em DATE
);

ALTER TABLE public.contas_pagar_corporativas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parcelas_conta_pagar ENABLE ROW LEVEL SECURITY;

COMMIT;
