-- financeirolb: recorrentes (cadastro + função + agendamento)
-- v1.1 - 2025-09-16 (fix: usar cron.schedule com schema correto)

BEGIN;

-- Cadastro de recorrentes (se ainda não existir)
CREATE TABLE IF NOT EXISTS public.recorrentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filial_id BIGINT,
  credor_id BIGINT REFERENCES public.entidades(id),
  categoria_id BIGINT,
  descricao TEXT NOT NULL,
  valor NUMERIC(14,2) NOT NULL CHECK (valor >= 0),
  dia_vencimento INT NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 28),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recorrentes_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano INT NOT NULL,
  mes INT NOT NULL CHECK (mes BETWEEN 1 AND 12),
  executado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  total_gerado INT NOT NULL
);

-- Função que gera os lançamentos do mês/ano
CREATE OR REPLACE FUNCTION public.gerar_recorrentes(pano INT, pmes INT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE 
  rec RECORD;
  nova_conta_id BIGINT;
  venc DATE;
BEGIN
  FOR rec IN 
    SELECT * FROM public.recorrentes WHERE ativo = TRUE
  LOOP
    venc := make_date(pano, pmes, rec.dia_vencimento);

    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema='public' AND table_name='contas_pagar_corporativas'
    ) THEN
      INSERT INTO public.contas_pagar_corporativas (filial_id, credor_id, descricao, valor_total, categoria_id, dt_vencimento)
      VALUES (rec.filial_id, rec.credor_id, concat(rec.descricao, ' ', to_char(venc, 'MM/YYYY')), rec.valor, rec.categoria_id, venc)
      RETURNING id INTO nova_conta_id;

      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema='public' AND table_name='parcelas_conta_pagar'
      ) THEN
        INSERT INTO public.parcelas_conta_pagar (conta_pagar_id, data_vencimento, valor_parcela, status)
        VALUES (nova_conta_id, venc, rec.valor, 'a_vencer');
      END IF;
    END IF;
  END LOOP;

  INSERT INTO public.recorrentes_log (ano, mes, total_gerado)
  VALUES (pano, pmes, (SELECT COUNT(*) FROM public.recorrentes WHERE ativo = TRUE));
END;
$$;

COMMIT;

-- Habilitar pg_cron no schema padrão "cron"
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Criar o job 1x/mês caso ainda não exista
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'financeirolb_recorrentes_mensal') THEN
    PERFORM cron.schedule(
      'financeirolb_recorrentes_mensal',
      '10 0 1 * *',
      $$ SELECT public.gerar_recorrentes(EXTRACT(year FROM current_date)::int,
                                         EXTRACT(month FROM current_date)::int) $$
    );
  END IF;
END $$;
